In [2]:
import numpy as np

## random numbers

In [9]:
data = np.random.rand(2, 3)
print(f"Array:{data}\nData type: {data.dtype}\nShape: {data.shape}\nDimension: {data.ndim} ")

Array:[[0.24577788 0.94960629 0.15470961]
 [0.54586196 0.44837587 0.04670139]]
Data type: float64
Shape: (2, 3)
Dimension: 2 


In [10]:
arr=np.array([1,2,5,7.8,1.25])
print(f"Array:{arr}\nData type: {arr.dtype}\nShape: {arr.shape}\nDimension: {arr.ndim} ")

Array:[1.   2.   5.   7.8  1.25]
Data type: float64
Shape: (5,)
Dimension: 1 


In [11]:
arr=np.array([[1,2,3,4],[4,3,2,1]])
print(f"Array:{arr}\nData type: {arr.dtype}\nShape: {arr.shape}\nDimension: {arr.ndim} ")

Array:[[1 2 3 4]
 [4 3 2 1]]
Data type: int64
Shape: (2, 4)
Dimension: 2 


In [16]:
print(f"Zeros array (10 elements): {np.zeros(10)}")
print(f"Zeros array (2x3): {np.zeros((2, 3))}")
print(f"Ones array (5 elements): {np.ones(5)}")
print(f"Ones array (2x3): {np.ones((2, 3))}")
print(f"Full array (2x3, value=10): {np.full((2, 3), 10)}")
print(f"Identity matrix (3x3): {np.eye(3)}")
print(f"Range 0-9: {np.arange(10)}")
print(f"Range 1-9: {np.arange(1, 10)}")
print(f"Linspace 1-10 (10 points): {np.linspace(1, 10, 10)}")
print(f"Linspace 1-10 (10 points, no endpoint): {np.linspace(1, 10, 10, endpoint=False)}")
print(f"Random array (10 elements): {np.random.rand(10)}")
print(f"Random array (2x3): {np.random.rand(2, 3)}")
print(f"Random integers 1-9 (10 elements): {np.random.randint(1, 10, 10)}")


Zeros array (10 elements): [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Zeros array (2x3): [[0. 0. 0.]
 [0. 0. 0.]]
Ones array (5 elements): [1. 1. 1. 1. 1.]
Ones array (2x3): [[1. 1. 1.]
 [1. 1. 1.]]
Full array (2x3, value=10): [[10 10 10]
 [10 10 10]]
Identity matrix (3x3): [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Range 0-9: [0 1 2 3 4 5 6 7 8 9]
Range 1-9: [1 2 3 4 5 6 7 8 9]
Linspace 1-10 (10 points): [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Linspace 1-10 (10 points, no endpoint): [1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]
Random array (10 elements): [0.66249831 0.79865392 0.02232382 0.29047169 0.5106659  0.34017188
 0.14360364 0.80074041 0.88694628 0.58250029]
Random array (2x3): [[0.75566269 0.53539719 0.08684981]
 [0.71278039 0.42093692 0.23415283]]
Random integers 1-9 (10 elements): [8 8 7 5 5 2 4 9 3 8]


## convert type

In [21]:

# Create an array with values from 0 to 18 (exclusive of 20), stepping by 2
arr = np.arange(0, 20, 2)
print(f"Original array: {arr}")
print(f"Data type: {arr.dtype}")

# Convert the integer array to float64 type
arrFloat = arr.astype(np.float64)
print(f"Float array: {arrFloat}")
print(f"Data type after conversion: {arrFloat.dtype}")


Original array: [ 0  2  4  6  8 10 12 14 16 18]
Data type: int64
Float array: [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
Data type after conversion: float64


## arithmetic with Arrays

In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) + np.array([[1, 2, 3], [4, 5, 6]])
print(f"Sum of two arrays: {arr}")

# readonly
print(f"Element-wise multiplication of arrays: {arr*arr}")
print(f"Element-wise subtraction of arrays: {arr-arr}")
print(f"Element-wise division of arrays: {1/arr}")
print(f"Element-wise power of arrays: {arr**2}")
arr_sum=arr+arr # write
print(f"Element-wise addition of arrays: {arr_sum}")
print(f"Element-wise greater than of arrays: {arr_sum>arr}")

Sum of two arrays: [[ 2  4  6]
 [ 8 10 12]]
Element-wise multiplication of arrays: [[  4  16  36]
 [ 64 100 144]]
Element-wise subtraction of arrays: [[0 0 0]
 [0 0 0]]
Element-wise division of arrays: [[0.5        0.25       0.16666667]
 [0.125      0.1        0.08333333]]
Element-wise power of arrays: [[  4  16  36]
 [ 64 100 144]]
Element-wise addition of arrays: [[ 4  8 12]
 [16 20 24]]
Element-wise greater than of arrays: [[ True  True  True]
 [ True  True  True]]


### index

In [33]:
arr = np.arange(0,10)
# readonly
print(f"arr == {arr}")
print(f"arr[5] == 5: {arr[5]}")
print(f"arr[5:8] == [5,6,7]: {arr[5:8]}")
print(f"arr[1] == 1: {arr[1]}")
print(f"arr[:] == {arr[:]}")

arr[5] == 5: 5
arr[5:8] == [5,6,7]: [5 6 7]
arr[1] == 1: 1
arr[:]==[0 1 2 3 4 5 6 7 8 9]


### copy data

In [42]:
arr = np.arange(0,10)
print(f"arr == {arr}")
slice_example = arr[2:4].copy()
print(f"arr_copy_slice == {slice_example}")
slice_example[:]=111
print(f"arr_set_value_to_all == {slice_example}")

arr == [0 1 2 3 4 5 6 7 8 9]
arr_copy_slice == [2 3]
arr_set_value == [111 111]


### multi dimension array

In [46]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f"arr == {arr}")
print(f"arr[1,2] is equal to{arr[1,2]}")

arr == [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr[1,2] is equal to6


### mask

In [59]:
arr = np.arange(0,21)
print(f"arr == {arr}")
print(f"are elements <100 == {arr<100}")
arr[arr<20]=8888 #write to arr
print(f"mask numbers less than 20 == {arr}")

arr == [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
are elements <100 == [ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True]
mask numbers less than 20 == [8888 8888 8888 8888 8888 8888 8888 8888 8888 8888 8888 8888 8888 8888
 8888 8888 8888 8888 8888 8888   20]


### transposition

In [63]:
arr = np.arange(15)
print(f"arr == {arr}")
arr = arr.reshape(3,5)
print(f"arr reshape {arr}")
print(f"arr transposition {arr.T}")
print(f"arr multiplication {np.dot(arr.T, arr)}")

arr == [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
arr reshape [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
arr transposition [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
arr multiplication [[125 140 155 170 185]
 [140 158 176 194 212]
 [155 176 197 218 239]
 [170 194 218 242 266]
 [185 212 239 266 293]]
