##Course - Introduction to Data Science - Univesp
##Week 2 Support Exercises

###1 - Load the NumPy and Pandas libraries

In [2]:
import pandas as pd
import numpy as np

###2 - Create an NDArray with the following values [1, 2.5, 7, -78, -0.9, 130, 25]

In [9]:
np.array([1, 2.5, 7, -78, -0.9, 130, 25])

array([  1. ,   2.5,   7. , -78. ,  -0.9, 130. ,  25. ])

###3 - Create an NDArray with values from 0 to 10

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###4 – Create a 2x5 NDArray with values of 1

In [14]:
# More efficient (creates the array in one step instead of creating two 1D arrays and then combining them)
np.ones((2, 5))

# works but is less efficient
np.array([
    np.ones(5),
    np.ones(5),
])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

###5 – Create an NDArray with values from 1 to 100, with intervals of 3.

In [15]:
np.array(np.arange(1,101,3))  # Use arange - you know the step

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

###6 – Show the square roots of the values from the NDArray created in exercise 5.

In [23]:
arr = np.array(np.arange(1,101,3))
arr_sqrt = np.sqrt(arr)
print(f"--- arr (Original) ---\n{arr}\n")
print(f"--- arr_sqrt (arr_sqrt) ---\n{arr_sqrt}\n")

--- arr (Original) ---
[  1   4   7  10  13  16  19  22  25  28  31  34  37  40  43  46  49  52
  55  58  61  64  67  70  73  76  79  82  85  88  91  94  97 100]

--- arr_sqrt (arr_sqrt) ---
[ 1.          2.          2.64575131  3.16227766  3.60555128  4.
  4.35889894  4.69041576  5.          5.29150262  5.56776436  5.83095189
  6.08276253  6.32455532  6.55743852  6.78232998  7.          7.21110255
  7.41619849  7.61577311  7.81024968  8.          8.18535277  8.36660027
  8.54400375  8.71779789  8.88819442  9.05538514  9.21954446  9.38083152
  9.53939201  9.69535971  9.8488578  10.        ]



###7 – Change the tenth position of the NDArray created in exercise 5 to double its value.

In [25]:
arr = np.array(np.arange(1,101,3))
print(f"--- arr (Original) ---\n{arr}\n")
arr[10] = arr[10] * 2
print(f"--- arr (arr[10] * 2) ---\n{arr}\n")

--- arr (Original) ---
[  1   4   7  10  13  16  19  22  25  28  31  34  37  40  43  46  49  52
  55  58  61  64  67  70  73  76  79  82  85  88  91  94  97 100]

--- arr (arr[10] * 2) ---
[  1   4   7  10  13  16  19  22  25  28  62  34  37  40  43  46  49  52
  55  58  61  64  67  70  73  76  79  82  85  88  91  94  97 100]



###8 – Execute the command to create a DataFrame with the data available in the notebook.

In [26]:
dados={'Empresa':['Microsoft', 'Google','Univesp','NVData Analytics','Power Bi Experience','USP'], 'Qtde Func':[1000, 1500,500, 100,100,499], 'Site':['https://www.microsoft.com/pt-br','https://www.google.com/','https://univesp.br/','https://www.nvdata.com.br/','https://powerbiexperience.com/pt/','https://www.usp.br/'],'Instagram':['@microsoft','@google','@univespoficial','@nv_data','@leokarpa','@usp.oficial'],'Criação':[1975,1998,2012,2019,2016,1934], 'País':['EUA','EUA','Brasil','Brasil','Brasil','Brasil']}

###9 – Execute a command that can identify the average number of employees that the listed companies have. Also report the sum of employees that the companies have.


In [36]:
df=pd.DataFrame(dados)
print(f"--- Average number of employees ---\n{df['Qtde Func'].mean()}\n")
print(f"--- Total sum of employees ---\n{df['Qtde Func'].sum()}\n")
df

--- Average number of employees ---
616.5

--- Total sum of employees ---
3699



Empresa  Qtde Func                               Site  \
0            Microsoft       1000    https://www.microsoft.com/pt-br   
1               Google       1500            https://www.google.com/   
2              Univesp        500                https://univesp.br/   
3     NVData Analytics        100         https://www.nvdata.com.br/   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   
5                  USP        499                https://www.usp.br/   

         Instagram  Criação    País  
0       @microsoft     1975     EUA  
1          @google     1998     EUA  
2  @univespoficial     2012  Brasil  
3         @nv_data     2019  Brasil  
4        @leokarpa     2016  Brasil  
5     @usp.oficial     1934  Brasil

###10 – Show the first 3 rows of the dataframe.

In [37]:
df[:3]

Empresa  Qtde Func                             Site        Instagram  \
0  Microsoft       1000  https://www.microsoft.com/pt-br       @microsoft   
1     Google       1500          https://www.google.com/          @google   
2    Univesp        500              https://univesp.br/  @univespoficial   

   Criação    País  
0     1975     EUA  
1     1998     EUA  
2     2012  Brasil

###11 – Show the last 3 rows of the dataframe.

In [38]:
df.tail(3)

Empresa  Qtde Func                               Site  \
3     NVData Analytics        100         https://www.nvdata.com.br/   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   
5                  USP        499                https://www.usp.br/   

      Instagram  Criação    País  
3      @nv_data     2019  Brasil  
4     @leokarpa     2016  Brasil  
5  @usp.oficial     1934  Brasil

###12 – List only the rows where companies were created in the last 10 years. Report the number of records.

In [39]:
df[df['Criação']>2015]

Empresa  Qtde Func                               Site  \
3     NVData Analytics        100         https://www.nvdata.com.br/   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   

   Instagram  Criação    País  
3   @nv_data     2019  Brasil  
4  @leokarpa     2016  Brasil

###13 – Let's imagine that in all companies there is 1 manager for every 23 employees. Create a column that shows the number of managers each company would have and then report how many managers we would have in total. (values don't need to be whole numbers, it's just an estimate).


In [53]:
df['Managers'] = df['Qtde Func'] / 23
df['Managers'] = df['Managers'].astype(int)
df

Empresa  Qtde Func                               Site  \
0            Microsoft       1000    https://www.microsoft.com/pt-br   
1               Google       1500            https://www.google.com/   
2              Univesp        500                https://univesp.br/   
3     NVData Analytics        100         https://www.nvdata.com.br/   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   
5                  USP        499                https://www.usp.br/   

         Instagram  Criação    País  Managers  
0       @microsoft     1975     EUA        43  
1          @google     1998     EUA        65  
2  @univespoficial     2012  Brasil        21  
3         @nv_data     2019  Brasil         4  
4        @leokarpa     2016  Brasil         4  
5     @usp.oficial     1934  Brasil        21